### PR TITLE
Documented gmail on the Web (closes #3)

### LINKED ISSUE #3: Document gmail + slow connection
Gmail will sometimes allow users to load a "HTML only" version of gmail - for slow connections. 

screenshot 2013-12-09 15 10 37

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@nrooney can you please review?

**Comment by nrooney** [comment]
Checked on two android devices, doesn't seem to happen. This may be because the connection was strong on both occasions, again, will give this another shot tomorrow.

**Comment by marcoscaceres** [comment]
Same with this one. No need to verify, just need you to check if what I wrote is ok :smile:

**Comment by nrooney** [comment]
Makes sense, you're good to go!

**Pull request merged**
