### PR TITLE
Add Tweetbot example

### PR DESCRIPTION
**Pull request by mathiasbynens**
My editor automatically removed trailing whitespace etc. Sans-whitespace diff: https://github.com/w3c-webmob/netinfo/pull/1/files?w=1

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Quick rebase?

**Comment by mathiasbynens** [comment]
Sure, hold on a second. Also resizing the images.

**Comment by marcoscaceres** [comment]
text looks good, btw! Thanks a lot for this!

**Comment by mathiasbynens** [comment]
Done. You’re welcome :)

**Pull request merged**
